### PR TITLE
Revert "add Japanese section 4.5 "

### PR DESCRIPTION
**Pull request by ogryzek**
Reverts ogryzek/go-programming#4

### CODE REVIEW

**Comment by ogryzek** [comment]
Should we create PRs against the upstream or here?

**Comment by shishi** [comment]
I think whichever as long as someone review them.

**Comment by shishi** [comment]
Perhaps, You don't want to review and be reviewed? I think it's natural with team, but you think don't need review, I'll follow.

**Comment by ogryzek** [comment]
@shishi you have already found some mistakes with my writing that help to give us better quality. I think that is valuable.  
  
I'm not sure if we want/need to review, but I think it's nice to have. Up to you though, if you merge immediately or wait for the pull request. It won't _break_ our code 😄 

Do you think it's better to wait on pull requests?

**Comment by ogryzek** [comment]
I felt it was better to create PRs to the upstream, so there's more visibility, but I suppose we can create a PR from our master to upstream master, and still have the same visibility. It just adds an additional step on our downstream fork.  
  
I don't really mind either way: wait for each other to review, merge immediately, PR against our fork vs upstream... anything is OK for me.

If you have an opinion, I will follow that 👍

**Comment by shishi** [comment]
OK, I'll submit PRs to upstream in the future. And I think review is essential thing, for quality and responsibility for products.

So If we don't have other Japanese speaker, I ask you to review my writings every time.

I'll close this PR and submit new PR to upstream for section 4.5.

**Comment by shishi** [comment]
Oh never mind. It was already merged. Thank you.

**Comment by ogryzek** [comment]
Oh yeah! I was confused and accidentally created this PR to revert the merge... my mistake! 😢

**Pull request closed without merging**
