### PR TITLE
add Japanese section 4.3

### PR DESCRIPTION
**Pull request by shishi**
Add Japanese 4.3.

I wonder why there is "[An Introduction to Programming in Go](https://www.golang-book.com/books/intro)" in this section.

Please review my pull requests in order 😃

### CODE REVIEW

**Comment by shishi** [comment]
Are you really OK about "An Introduction to Programming in Go" in this section?

**Comment by ogryzek** [comment]
Yes, it's good to have, but you're right. It should be something like:

*Further Reading*: Caleb Doxsey's [An Introduction to Programming in Go](https://www.golang-book.com/books/intro)

OR 

*Recommended Reading*: Caleb Doxsey's [An Introduction to Programming in Go](https://www.golang-book.com/books/intro)

**Comment by shishi** [comment]
Well, OK, I still don't think it's reasonable this book is here, though this book is super great.

But it's not a mistake, I trust you. Maybe I don't understand something in this context.

**Comment by ogryzek** [comment]
@shishi You make a good point. I think you're right, so let's remove it from English and Japanese. I added it, because Todd mentions it as a great resource during the lecture, however it probably isn't appropriate, and not directly related to the topic. 👍

**Comment by shishi** [comment]
Thank you for accepting. I thinks it's too sudden, so we have to introduce in better section like appendix.

I'll fix this also in next pull request.

**Comment by ogryzek** [comment]
Yeah, I agree! Very reasonable 👍

**Pull request merged**
